version: "3.9"
services:
  api:
    build: ../api
    environment:
      WEB_ORIGIN: http://localhost:3000
      SEED: "1"
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  web:
    build: ../web
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - api
